export interface Route {
  id: string
  flightNumber: string
  from: string
  fromCode: string
  to: string
  toCode: string
  region: string
  duration: string
  frequency: string
  fromPrice: number
  popular?: boolean
  type: "passenger" | "cargo" | "supersonic"
  codeshare?: string
  seasonal?: "summer" | "autumn"
  aircraft?: string
  terminated?: boolean
}

export const routes: Route[] = [
  // Western Europe (RJA101-124)
  {
    id: "rja101",
    flightNumber: "RJA101",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "London Heathrow",
    toCode: "EGLL",
    region: "europe",
    duration: "12h 30m",
    frequency: "Daily",
    fromPrice: 85000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja103",
    flightNumber: "RJA103",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Paris CDG",
    toCode: "LFPG",
    region: "europe",
    duration: "13h 10m",
    frequency: "Daily",
    fromPrice: 88000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja105",
    flightNumber: "RJA105",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Madrid",
    toCode: "LEMD",
    region: "europe",
    duration: "14h 20m",
    frequency: "Daily",
    fromPrice: 90000,
    type: "passenger",
  },
  {
    id: "rja107",
    flightNumber: "RJA107",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Amsterdam",
    toCode: "EHAM",
    region: "europe",
    duration: "12h 45m",
    frequency: "Daily",
    fromPrice: 86000,
    type: "passenger",
  },
  {
    id: "rja109",
    flightNumber: "RJA109",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Milan",
    toCode: "LIMC",
    region: "europe",
    duration: "13h 30m",
    frequency: "5x weekly",
    fromPrice: 87000,
    type: "passenger",
  },
  {
    id: "rja111",
    flightNumber: "RJA111",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Frankfurt",
    toCode: "EDDF",
    region: "europe",
    duration: "12h 50m",
    frequency: "Daily",
    fromPrice: 86500,
    type: "passenger",
  },
  {
    id: "rja113",
    flightNumber: "RJA113",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Zurich",
    toCode: "LSZH",
    region: "europe",
    duration: "13h 15m",
    frequency: "5x weekly",
    fromPrice: 89000,
    type: "passenger",
  },
  {
    id: "rja115",
    flightNumber: "RJA115",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Manchester",
    toCode: "EGCC",
    region: "europe",
    duration: "13h 0m",
    frequency: "4x weekly",
    fromPrice: 84000,
    type: "passenger",
  },
  {
    id: "rja117",
    flightNumber: "RJA117",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Lisbon",
    toCode: "LPPT",
    region: "europe",
    duration: "15h 10m",
    frequency: "3x weekly",
    fromPrice: 91000,
    type: "passenger",
  },
  {
    id: "rja119",
    flightNumber: "RJA119",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Brussels",
    toCode: "EBBR",
    region: "europe",
    duration: "13h 20m",
    frequency: "4x weekly",
    fromPrice: 87500,
    type: "passenger",
  },
  {
    id: "rja121",
    flightNumber: "RJA121",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Barcelona",
    toCode: "LEBL",
    region: "europe",
    duration: "14h 30m",
    frequency: "4x weekly",
    fromPrice: 89500,
    type: "passenger",
  },
  {
    id: "rja123",
    flightNumber: "RJA123",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Ibiza",
    toCode: "LEIB",
    region: "europe",
    duration: "15h 0m",
    frequency: "2x weekly",
    fromPrice: 92000,
    type: "passenger",
  },

  // Northern Europe (RJA131-138)
  {
    id: "rja131",
    flightNumber: "RJA131",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Stockholm",
    toCode: "ESSA",
    region: "europe",
    duration: "11h 50m",
    frequency: "4x weekly",
    fromPrice: 83000,
    type: "passenger",
  },
  {
    id: "rja133",
    flightNumber: "RJA133",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Copenhagen",
    toCode: "EKCH",
    region: "europe",
    duration: "12h 10m",
    frequency: "5x weekly",
    fromPrice: 84500,
    type: "passenger",
  },
  {
    id: "rja135",
    flightNumber: "RJA135",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Oslo",
    toCode: "ENGM",
    region: "europe",
    duration: "11h 40m",
    frequency: "3x weekly",
    fromPrice: 85000,
    type: "passenger",
  },
  {
    id: "rja137",
    flightNumber: "RJA137",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Helsinki",
    toCode: "EFHK",
    region: "europe",
    duration: "10h 30m",
    frequency: "4x weekly",
    fromPrice: 81000,
    type: "passenger",
  },

  // Central & Eastern Europe (RJA141-150)
  {
    id: "rja141",
    flightNumber: "RJA141",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Munich",
    toCode: "EDDM",
    region: "europe",
    duration: "12h 55m",
    frequency: "5x weekly",
    fromPrice: 86000,
    type: "passenger",
  },
  {
    id: "rja143",
    flightNumber: "RJA143",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Warsaw",
    toCode: "EPWA",
    region: "europe",
    duration: "11h 30m",
    frequency: "4x weekly",
    fromPrice: 79000,
    type: "passenger",
  },
  {
    id: "rja145",
    flightNumber: "RJA145",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Budapest",
    toCode: "LHBP",
    region: "europe",
    duration: "12h 20m",
    frequency: "3x weekly",
    fromPrice: 80000,
    type: "passenger",
  },
  {
    id: "rja147",
    flightNumber: "RJA147",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Vienna",
    toCode: "LOWW",
    region: "europe",
    duration: "12h 40m",
    frequency: "4x weekly",
    fromPrice: 82000,
    type: "passenger",
  },
  {
    id: "rja149",
    flightNumber: "RJA149",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Prague",
    toCode: "LKPR",
    region: "europe",
    duration: "12h 30m",
    frequency: "3x weekly",
    fromPrice: 81500,
    type: "passenger",
  },

  // North America - United States (RJA151-168)
  {
    id: "rja151",
    flightNumber: "RJA151",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "New York JFK",
    toCode: "KJFK",
    region: "north-america",
    duration: "13h 15m",
    frequency: "Daily",
    fromPrice: 95000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja153",
    flightNumber: "RJA153",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Boston",
    toCode: "KBOS",
    region: "north-america",
    duration: "13h 30m",
    frequency: "Daily",
    fromPrice: 93000,
    type: "passenger",
  },
  {
    id: "rja155",
    flightNumber: "RJA155",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Washington D.C.",
    toCode: "KIAD",
    region: "north-america",
    duration: "13h 45m",
    frequency: "Daily",
    fromPrice: 94000,
    type: "passenger",
  },
  {
    id: "rja157",
    flightNumber: "RJA157",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Las Vegas",
    toCode: "KLAS",
    region: "north-america",
    duration: "11h 30m",
    frequency: "5x weekly",
    fromPrice: 88000,
    type: "passenger",
  },
  {
    id: "rja159",
    flightNumber: "RJA159",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Honolulu",
    toCode: "KHNL",
    region: "north-america",
    duration: "7h 45m",
    frequency: "Daily",
    fromPrice: 65000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja161",
    flightNumber: "RJA161",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Miami",
    toCode: "KMIA",
    region: "north-america",
    duration: "14h 20m",
    frequency: "4x weekly",
    fromPrice: 98000,
    type: "passenger",
  },
  {
    id: "rja163",
    flightNumber: "RJA163",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "San Francisco",
    toCode: "KSFO",
    region: "north-america",
    duration: "10h 30m",
    frequency: "Daily",
    fromPrice: 89000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja165",
    flightNumber: "RJA165",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Atlanta",
    toCode: "KATL",
    region: "north-america",
    duration: "13h 50m",
    frequency: "Daily",
    fromPrice: 96000,
    type: "passenger",
  },
  {
    id: "rja167",
    flightNumber: "RJA167",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Los Angeles",
    toCode: "KLAX",
    region: "north-america",
    duration: "10h 45m",
    frequency: "Daily",
    fromPrice: 87000,
    popular: true,
    type: "passenger",
  },

  // North America - Canada (RJA171-176) - Note: RJA171/172 is Moscow in main list
  {
    id: "rja172",
    flightNumber: "RJA172",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Moscow Sheremetyevo",
    toCode: "UUEE",
    region: "russia",
    duration: "10h 0m",
    frequency: "5x weekly",
    fromPrice: 76000,
    type: "passenger",
    terminated: true,
  },
  {
    id: "rja173",
    flightNumber: "RJA173",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Halifax",
    toCode: "CYHZ",
    region: "north-america",
    duration: "13h 30m",
    frequency: "3x weekly",
    fromPrice: 89000,
    type: "passenger",
  },
  {
    id: "rja175",
    flightNumber: "RJA175",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Toronto",
    toCode: "CYYZ",
    region: "north-america",
    duration: "12h 30m",
    frequency: "Daily",
    fromPrice: 91000,
    type: "passenger",
  },

  // North America - Mexico (RJA179-180)
  {
    id: "rja179",
    flightNumber: "RJA179",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Mexico City",
    toCode: "MMMX",
    region: "north-america",
    duration: "13h 20m",
    frequency: "4x weekly",
    fromPrice: 94000,
    type: "passenger",
  },

  // South America (RJA181-186)
  {
    id: "rja181",
    flightNumber: "RJA181",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "São Paulo",
    toCode: "SBGR",
    region: "south-america",
    duration: "24h 30m",
    frequency: "3x weekly",
    fromPrice: 145000,
    type: "passenger",
  },
  {
    id: "rja183",
    flightNumber: "RJA183",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Bogotá",
    toCode: "SKBO",
    region: "south-america",
    duration: "18h 45m",
    frequency: "3x weekly",
    fromPrice: 135000,
    type: "passenger",
  },
  {
    id: "rja185",
    flightNumber: "RJA185",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Santiago",
    toCode: "SCEL",
    region: "south-america",
    duration: "22h 15m",
    frequency: "2x weekly",
    fromPrice: 142000,
    type: "passenger",
  },

  // Russia (RJA187-188, RJA419-420)
  {
    id: "rja187",
    flightNumber: "RJA187",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "St. Petersburg",
    toCode: "ULLI",
    region: "russia",
    duration: "10h 20m",
    frequency: "4x weekly",
    fromPrice: 78000,
    type: "passenger",
    terminated: true,
  },
  {
    id: "rja419",
    flightNumber: "RJA419",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Vladivostok",
    toCode: "UHWW",
    region: "russia",
    duration: "2h 30m",
    frequency: "Daily",
    fromPrice: 35000,
    type: "passenger",
    terminated: true,
  },

  // Middle East (RJA201-222)
  {
    id: "rja201",
    flightNumber: "RJA201",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Dubai",
    toCode: "OMDB",
    region: "middle-east",
    duration: "10h 30m",
    frequency: "Daily",
    fromPrice: 72000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja203",
    flightNumber: "RJA203",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Istanbul",
    toCode: "LTFM",
    region: "middle-east",
    duration: "12h 15m",
    frequency: "Daily",
    fromPrice: 79000,
    type: "passenger",
  },
  {
    id: "rja205",
    flightNumber: "RJA205",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Abu Dhabi",
    toCode: "OMAA",
    region: "middle-east",
    duration: "10h 45m",
    frequency: "5x weekly",
    fromPrice: 73000,
    type: "passenger",
  },
  {
    id: "rja207",
    flightNumber: "RJA207",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Doha",
    toCode: "OTHH",
    region: "middle-east",
    duration: "11h 0m",
    frequency: "Daily",
    fromPrice: 74000,
    type: "passenger",
  },
  {
    id: "rja209",
    flightNumber: "RJA209",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Riyadh",
    toCode: "OERK",
    region: "middle-east",
    duration: "11h 30m",
    frequency: "4x weekly",
    fromPrice: 76000,
    type: "passenger",
  },
  {
    id: "rja211",
    flightNumber: "RJA211",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Jeddah",
    toCode: "OEJN",
    region: "middle-east",
    duration: "12h 0m",
    frequency: "3x weekly",
    fromPrice: 77000,
    type: "passenger",
  },
  {
    id: "rja213",
    flightNumber: "RJA213",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Kuwait City",
    toCode: "OKBK",
    region: "middle-east",
    duration: "11h 15m",
    frequency: "3x weekly",
    fromPrice: 75000,
    type: "passenger",
  },
  {
    id: "rja215",
    flightNumber: "RJA215",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Muscat",
    toCode: "OOMS",
    region: "middle-east",
    duration: "10h 50m",
    frequency: "3x weekly",
    fromPrice: 74500,
    type: "passenger",
  },
  {
    id: "rja217",
    flightNumber: "RJA217",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Manama",
    toCode: "OBBI",
    region: "middle-east",
    duration: "11h 10m",
    frequency: "2x weekly",
    fromPrice: 75500,
    type: "passenger",
  },
  {
    id: "rja219",
    flightNumber: "RJA219",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Dammam",
    toCode: "OEDF",
    region: "middle-east",
    duration: "11h 25m",
    frequency: "2x weekly",
    fromPrice: 76500,
    type: "passenger",
  },
  {
    id: "rja221",
    flightNumber: "RJA221",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Amman",
    toCode: "OJAI",
    region: "middle-east",
    duration: "12h 30m",
    frequency: "2x weekly",
    fromPrice: 78500,
    type: "passenger",
  },

  // Southeast Asia (RJA231-252)
  {
    id: "rja231",
    flightNumber: "RJA231",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Singapore",
    toCode: "WSSS",
    region: "southeast-asia",
    duration: "7h 20m",
    frequency: "Daily",
    fromPrice: 45000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja233",
    flightNumber: "RJA233",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Ho Chi Minh City",
    toCode: "VVTS",
    region: "southeast-asia",
    duration: "6h 30m",
    frequency: "Daily",
    fromPrice: 42000,
    type: "passenger",
  },
  {
    id: "rja235",
    flightNumber: "RJA235",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Manila",
    toCode: "RPLL",
    region: "southeast-asia",
    duration: "4h 45m",
    frequency: "Daily",
    fromPrice: 38000,
    type: "passenger",
  },
  {
    id: "rja237",
    flightNumber: "RJA237",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Kuala Lumpur",
    toCode: "WMKK",
    region: "southeast-asia",
    duration: "7h 30m",
    frequency: "Daily",
    fromPrice: 46000,
    type: "passenger",
  },
  {
    id: "rja239",
    flightNumber: "RJA239",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Bangkok",
    toCode: "VTBS",
    region: "southeast-asia",
    duration: "6h 50m",
    frequency: "Daily",
    fromPrice: 44000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja241",
    flightNumber: "RJA241",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Chiang Mai",
    toCode: "VTCC",
    region: "southeast-asia",
    duration: "6h 20m",
    frequency: "5x weekly",
    fromPrice: 43000,
    type: "passenger",
  },
  {
    id: "rja243",
    flightNumber: "RJA243",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Kota Kinabalu",
    toCode: "WBKK",
    region: "southeast-asia",
    duration: "6h 10m",
    frequency: "4x weekly",
    fromPrice: 41000,
    type: "passenger",
  },
  {
    id: "rja245",
    flightNumber: "RJA245",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Penang",
    toCode: "WMKP",
    region: "southeast-asia",
    duration: "7h 15m",
    frequency: "4x weekly",
    fromPrice: 45000,
    type: "passenger",
  },
  {
    id: "rja247",
    flightNumber: "RJA247",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Jakarta",
    toCode: "WIII",
    region: "southeast-asia",
    duration: "7h 40m",
    frequency: "Daily",
    fromPrice: 47000,
    type: "passenger",
  },
  {
    id: "rja249",
    flightNumber: "RJA249",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Makassar",
    toCode: "WAAA",
    region: "southeast-asia",
    duration: "7h 50m",
    frequency: "3x weekly",
    fromPrice: 48000,
    type: "passenger",
  },
  {
    id: "rja251",
    flightNumber: "RJA251",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Can Tho",
    toCode: "VVCT",
    region: "southeast-asia",
    duration: "6h 40m",
    frequency: "3x weekly",
    fromPrice: 41500,
    type: "passenger",
  },

  // South Asia (RJA253-254, RJA347-356, RJA064-103)
  {
    id: "rja253",
    flightNumber: "RJA253",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Mumbai",
    toCode: "VABB",
    region: "south-asia",
    duration: "9h 30m",
    frequency: "Daily",
    fromPrice: 58000,
    type: "passenger",
  },
  {
    id: "rja064",
    flightNumber: "RJA064",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Shirdi",
    toCode: "VASD",
    region: "south-asia",
    duration: "9h 45m",
    frequency: "3x weekly",
    fromPrice: 59000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja067",
    flightNumber: "RJA067",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "New Delhi",
    toCode: "VIDP",
    region: "south-asia",
    duration: "9h 15m",
    frequency: "Daily",
    fromPrice: 57000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja076",
    flightNumber: "RJA076",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Raipur",
    toCode: "VERP",
    region: "south-asia",
    duration: "9h 50m",
    frequency: "2x weekly",
    fromPrice: 59500,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja078",
    flightNumber: "RJA078",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Nagpur",
    toCode: "VANP",
    region: "south-asia",
    duration: "9h 40m",
    frequency: "2x weekly",
    fromPrice: 59000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja079",
    flightNumber: "RJA079",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Ahmedabad",
    toCode: "VAAH",
    region: "south-asia",
    duration: "9h 20m",
    frequency: "3x weekly",
    fromPrice: 58500,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja080",
    flightNumber: "RJA080",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Port Blair",
    toCode: "VOPB",
    region: "south-asia",
    duration: "8h 30m",
    frequency: "2x weekly",
    fromPrice: 54000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja069",
    flightNumber: "RJA069",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Chennai",
    toCode: "VOMM",
    region: "south-asia",
    duration: "9h 10m",
    frequency: "Daily",
    fromPrice: 56000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja070",
    flightNumber: "RJA070",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Guwahati",
    toCode: "VEGT",
    region: "south-asia",
    duration: "8h 0m",
    frequency: "3x weekly",
    fromPrice: 52000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja071",
    flightNumber: "RJA071",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Bengaluru",
    toCode: "VOBL",
    region: "south-asia",
    duration: "9h 25m",
    frequency: "Daily",
    fromPrice: 57500,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja072",
    flightNumber: "RJA072",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Hyderabad",
    toCode: "VOHS",
    region: "south-asia",
    duration: "9h 35m",
    frequency: "5x weekly",
    fromPrice: 58000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja100",
    flightNumber: "RJA100",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Dhaka",
    toCode: "VGHS",
    region: "south-asia",
    duration: "8h 15m",
    frequency: "5x weekly",
    fromPrice: 53000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja101cs",
    flightNumber: "RJA101",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Sylhet",
    toCode: "VGSY",
    region: "south-asia",
    duration: "8h 30m",
    frequency: "3x weekly",
    fromPrice: 54000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja102",
    flightNumber: "RJA102",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Chittagong",
    toCode: "VGEG",
    region: "south-asia",
    duration: "8h 20m",
    frequency: "3x weekly",
    fromPrice: 53500,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja103",
    flightNumber: "RJA103",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Kathmandu",
    toCode: "VNKT",
    region: "south-asia",
    duration: "8h 20m",
    frequency: "4x weekly",
    fromPrice: 52000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja349",
    flightNumber: "RJA349",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Paro",
    toCode: "VQPR",
    region: "south-asia",
    duration: "8h 40m",
    frequency: "2x weekly",
    fromPrice: 55000,
    type: "passenger",
  },
  {
    id: "rja351",
    flightNumber: "RJA351",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Mattala",
    toCode: "VCRI",
    region: "south-asia",
    duration: "9h 50m",
    frequency: "2x weekly",
    fromPrice: 60000,
    type: "passenger",
  },
  {
    id: "rja353",
    flightNumber: "RJA353",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Sylhet",
    toCode: "VGSY",
    region: "south-asia",
    duration: "8h 30m",
    frequency: "3x weekly",
    fromPrice: 54000,
    type: "passenger",
  },

  // Central Asia (RJA169-174, RJA329-346)
  {
    id: "rja169",
    flightNumber: "RJA169",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Astana",
    toCode: "UACC",
    region: "central-asia",
    duration: "7h 30m",
    frequency: "4x weekly",
    fromPrice: 48000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja170",
    flightNumber: "RJA170",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Almaty",
    toCode: "UAAA",
    region: "central-asia",
    duration: "7h 15m",
    frequency: "5x weekly",
    fromPrice: 47000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja171cs",
    flightNumber: "RJA171",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Aktau",
    toCode: "UATE",
    region: "central-asia",
    duration: "8h 0m",
    frequency: "2x weekly",
    fromPrice: 50000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja172cs",
    flightNumber: "RJA172",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Atyrau",
    toCode: "UATG",
    region: "central-asia",
    duration: "8h 10m",
    frequency: "2x weekly",
    fromPrice: 50500,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja173cs",
    flightNumber: "RJA173",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Shymkent",
    toCode: "UAII",
    region: "central-asia",
    duration: "7h 45m",
    frequency: "2x weekly",
    fromPrice: 49000,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja174",
    flightNumber: "BLA174",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Karaganda",
    toCode: "UAKK",
    region: "central-asia",
    duration: "7h 50m",
    frequency: "Weekly",
    fromPrice: 49500,
    type: "passenger",
    codeshare: "Codeshare",
  },
  {
    id: "rja329",
    flightNumber: "RJA329",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Ulaanbaatar",
    toCode: "ZMCK",
    region: "central-asia",
    duration: "4h 30m",
    frequency: "5x weekly",
    fromPrice: 37000,
    type: "passenger",
  },
  {
    id: "rja331",
    flightNumber: "RJA331",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Almaty",
    toCode: "UAAA",
    region: "central-asia",
    duration: "7h 15m",
    frequency: "5x weekly",
    fromPrice: 47000,
    type: "passenger",
  },
  {
    id: "rja333",
    flightNumber: "RJA333",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Astana",
    toCode: "UACC",
    region: "central-asia",
    duration: "7h 30m",
    frequency: "4x weekly",
    fromPrice: 48000,
    type: "passenger",
  },
  {
    id: "rja335",
    flightNumber: "RJA335",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Tashkent",
    toCode: "UTTT",
    region: "central-asia",
    duration: "8h 0m",
    frequency: "3x weekly",
    fromPrice: 51000,
    type: "passenger",
  },
  {
    id: "rja337",
    flightNumber: "RJA337",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Bishkek",
    toCode: "UCFM",
    region: "central-asia",
    duration: "7h 45m",
    frequency: "2x weekly",
    fromPrice: 49500,
    type: "passenger",
  },
  {
    id: "rja339",
    flightNumber: "RJA339",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Dushanbe",
    toCode: "UTDD",
    region: "central-asia",
    duration: "8h 15m",
    frequency: "2x weekly",
    fromPrice: 52000,
    type: "passenger",
  },
  {
    id: "rja341",
    flightNumber: "RJA341",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Tbilisi",
    toCode: "UGTB",
    region: "central-asia",
    duration: "10h 30m",
    frequency: "3x weekly",
    fromPrice: 65000,
    type: "passenger",
  },
  {
    id: "rja343",
    flightNumber: "RJA343",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Yerevan",
    toCode: "UDYZ",
    region: "central-asia",
    duration: "10h 45m",
    frequency: "2x weekly",
    fromPrice: 66000,
    type: "passenger",
  },
  {
    id: "rja345",
    flightNumber: "RJA345",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Baku",
    toCode: "UBBB",
    region: "central-asia",
    duration: "10h 20m",
    frequency: "3x weekly",
    fromPrice: 64000,
    type: "passenger",
  },

  // Medium-Haul Asia-Pacific (RJA281-328)
  {
    id: "rja281",
    flightNumber: "RJA281",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Hanoi",
    toCode: "VVNB",
    region: "southeast-asia",
    duration: "5h 50m",
    frequency: "Daily",
    fromPrice: 40000,
    type: "passenger",
  },
  {
    id: "rja283",
    flightNumber: "RJA283",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Da Nang",
    toCode: "VVDN",
    region: "southeast-asia",
    duration: "5h 30m",
    frequency: "5x weekly",
    fromPrice: 39000,
    type: "passenger",
  },
  {
    id: "rja285",
    flightNumber: "RJA285",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Nha Trang",
    toCode: "CXR",
    region: "southeast-asia",
    duration: "6h 0m",
    frequency: "3x weekly",
    fromPrice: 41000,
    type: "passenger",
  },
  {
    id: "rja287",
    flightNumber: "RJA287",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Phu Quoc",
    toCode: "VVPQ",
    region: "southeast-asia",
    duration: "7h 0m",
    frequency: "3x weekly",
    fromPrice: 44000,
    type: "passenger",
  },
  {
    id: "rja289",
    flightNumber: "RJA289",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Kalibo (Boracay)",
    toCode: "RPVK",
    region: "southeast-asia",
    duration: "5h 15m",
    frequency: "4x weekly",
    fromPrice: 40000,
    type: "passenger",
  },
  {
    id: "rja291",
    flightNumber: "RJA291",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Iloilo",
    toCode: "RPVI",
    region: "southeast-asia",
    duration: "5h 0m",
    frequency: "3x weekly",
    fromPrice: 39000,
    type: "passenger",
  },
  {
    id: "rja293",
    flightNumber: "RJA293",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "General Santos",
    toCode: "RPMR",
    region: "southeast-asia",
    duration: "5h 30m",
    frequency: "2x weekly",
    fromPrice: 41000,
    type: "passenger",
  },
  {
    id: "rja295",
    flightNumber: "RJA295",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Yogyakarta",
    toCode: "WAHI",
    region: "southeast-asia",
    duration: "7h 30m",
    frequency: "4x weekly",
    fromPrice: 46000,
    type: "passenger",
  },
  {
    id: "rja297",
    flightNumber: "RJA297",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Semarang",
    toCode: "WIIS",
    region: "southeast-asia",
    duration: "7h 45m",
    frequency: "3x weekly",
    fromPrice: 47000,
    type: "passenger",
  },
  {
    id: "rja299",
    flightNumber: "RJA299",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Balikpapan",
    toCode: "WALL",
    region: "southeast-asia",
    duration: "6h 50m",
    frequency: "3x weekly",
    fromPrice: 44000,
    type: "passenger",
  },
  {
    id: "rja301ap",
    flightNumber: "RJA301",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Manado",
    toCode: "WAMM",
    region: "southeast-asia",
    duration: "6h 30m",
    frequency: "3x weekly",
    fromPrice: 43000,
    type: "passenger",
  },
  {
    id: "rja303ap",
    flightNumber: "RJA303",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Banda Aceh",
    toCode: "WITT",
    region: "southeast-asia",
    duration: "8h 30m",
    frequency: "2x weekly",
    fromPrice: 52000,
    type: "passenger",
  },
  {
    id: "rja305ap",
    flightNumber: "RJA305",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Lombok Praya",
    toCode: "LOP",
    region: "southeast-asia",
    duration: "8h 0m",
    frequency: "3x weekly",
    fromPrice: 50000,
    type: "passenger",
  },
  {
    id: "rja307ap",
    flightNumber: "RJA307",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Kuching",
    toCode: "WBGG",
    region: "southeast-asia",
    duration: "6h 40m",
    frequency: "3x weekly",
    fromPrice: 43000,
    type: "passenger",
  },
  {
    id: "rja309ap",
    flightNumber: "RJA309",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Langkawi",
    toCode: "WMKL",
    region: "southeast-asia",
    duration: "7h 45m",
    frequency: "3x weekly",
    fromPrice: 48000,
    type: "passenger",
  },
  {
    id: "rja311",
    flightNumber: "RJA311",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Krabi",
    toCode: "VTSG",
    region: "southeast-asia",
    duration: "7h 10m",
    frequency: "4x weekly",
    fromPrice: 45000,
    type: "passenger",
  },
  {
    id: "rja313",
    flightNumber: "RJA313",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Hat Yai",
    toCode: "VTSS",
    region: "southeast-asia",
    duration: "7h 0m",
    frequency: "2x weekly",
    fromPrice: 44000,
    type: "passenger",
  },
  {
    id: "rja315",
    flightNumber: "RJA315",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Udon Thani",
    toCode: "VTUD",
    region: "southeast-asia",
    duration: "6h 30m",
    frequency: "2x weekly",
    fromPrice: 42000,
    type: "passenger",
  },
  {
    id: "rja317",
    flightNumber: "RJA317",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Luang Prabang",
    toCode: "VLLB",
    region: "southeast-asia",
    duration: "6h 15m",
    frequency: "2x weekly",
    fromPrice: 41000,
    type: "passenger",
  },
  {
    id: "rja319",
    flightNumber: "RJA319",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Mandalay",
    toCode: "VYMD",
    region: "southeast-asia",
    duration: "7h 30m",
    frequency: "2x weekly",
    fromPrice: 47000,
    type: "passenger",
  },
  {
    id: "rja321",
    flightNumber: "RJA321",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Sihanoukville",
    toCode: "VDSV",
    region: "southeast-asia",
    duration: "6h 50m",
    frequency: "2x weekly",
    fromPrice: 44000,
    type: "passenger",
  },
  {
    id: "rja323",
    flightNumber: "RJA323",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Bandar Seri Begawan",
    toCode: "WBSB",
    region: "southeast-asia",
    duration: "6h 20m",
    frequency: "3x weekly",
    fromPrice: 42000,
    type: "passenger",
  },
  {
    id: "rja325",
    flightNumber: "RJA325",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Gan Island",
    toCode: "VRMG",
    region: "south-asia",
    duration: "10h 30m",
    frequency: "2x weekly",
    fromPrice: 68000,
    type: "passenger",
  },
  {
    id: "rja327",
    flightNumber: "RJA327",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Dili",
    toCode: "WPDL",
    region: "southeast-asia",
    duration: "8h 15m",
    frequency: "Weekly",
    fromPrice: 51000,
    type: "passenger",
  },

  // Oceania (RJA301-310)
  {
    id: "rja301",
    flightNumber: "RJA301",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Sydney",
    toCode: "YSSY",
    region: "oceania",
    duration: "9h 45m",
    frequency: "Daily",
    fromPrice: 68000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja303",
    flightNumber: "RJA303",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Perth",
    toCode: "YPPH",
    region: "oceania",
    duration: "10h 30m",
    frequency: "5x weekly",
    fromPrice: 70000,
    type: "passenger",
  },
  {
    id: "rja305",
    flightNumber: "RJA305",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Melbourne",
    toCode: "YMML",
    region: "oceania",
    duration: "10h 15m",
    frequency: "Daily",
    fromPrice: 69000,
    type: "passenger",
  },
  {
    id: "rja307",
    flightNumber: "RJA307",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Brisbane",
    toCode: "YBBN",
    region: "oceania",
    duration: "9h 20m",
    frequency: "5x weekly",
    fromPrice: 67000,
    type: "passenger",
  },
  {
    id: "rja309",
    flightNumber: "RJA309",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Auckland",
    toCode: "NZAA",
    region: "oceania",
    duration: "11h 0m",
    frequency: "5x weekly",
    fromPrice: 72000,
    type: "passenger",
  },

  // East Asia - Short-Haul (RJA401-420, RJA461-484)
  {
    id: "rja401",
    flightNumber: "RJA401",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Seoul Incheon",
    toCode: "RKSI",
    region: "east-asia",
    duration: "2h 30m",
    frequency: "Multiple daily",
    fromPrice: 28000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja403",
    flightNumber: "RJA403",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Busan",
    toCode: "RKPK",
    region: "east-asia",
    duration: "2h 15m",
    frequency: "Daily",
    fromPrice: 26000,
    type: "passenger",
  },
  {
    id: "rja405",
    flightNumber: "RJA405",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Jeju",
    toCode: "RKPC",
    region: "east-asia",
    duration: "2h 45m",
    frequency: "Daily",
    fromPrice: 29000,
    type: "passenger",
  },
  {
    id: "rja407",
    flightNumber: "RJA407",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Hong Kong",
    toCode: "VHHH",
    region: "east-asia",
    duration: "4h 50m",
    frequency: "Daily",
    fromPrice: 39000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja409",
    flightNumber: "RJA409",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Macau",
    toCode: "VMMC",
    region: "east-asia",
    duration: "5h 0m",
    frequency: "5x weekly",
    fromPrice: 40000,
    type: "passenger",
  },
  {
    id: "rja411",
    flightNumber: "RJA411",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Taipei Songshan",
    toCode: "RCSS",
    region: "east-asia",
    duration: "3h 50m",
    frequency: "Daily",
    fromPrice: 35000,
    type: "passenger",
  },
  {
    id: "rja413",
    flightNumber: "RJA413",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Shenzhen",
    toCode: "ZGSZ",
    region: "east-asia",
    duration: "5h 10m",
    frequency: "Daily",
    fromPrice: 41000,
    type: "passenger",
  },
  {
    id: "rja415",
    flightNumber: "RJA415",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Beijing Capital",
    toCode: "ZBAA",
    region: "east-asia",
    duration: "4h 0m",
    frequency: "Daily",
    fromPrice: 36000,
    type: "passenger",
  },
  {
    id: "rja417",
    flightNumber: "RJA417",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Hangzhou",
    toCode: "ZSHC",
    region: "east-asia",
    duration: "3h 30m",
    frequency: "5x weekly",
    fromPrice: 34000,
    type: "passenger",
  },
  {
    id: "rja461",
    flightNumber: "RJA461",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Shanghai Pudong",
    toCode: "ZSPD",
    region: "east-asia",
    duration: "3h 15m",
    frequency: "Multiple daily",
    fromPrice: 33000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja463",
    flightNumber: "RJA463",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Shanghai Hongqiao",
    toCode: "ZSSS",
    region: "east-asia",
    duration: "3h 10m",
    frequency: "Daily",
    fromPrice: 32000,
    type: "passenger",
  },
  {
    id: "rja465",
    flightNumber: "RJA465",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Guangzhou",
    toCode: "ZGGG",
    region: "east-asia",
    duration: "5h 20m",
    frequency: "Daily",
    fromPrice: 42000,
    type: "passenger",
  },
  {
    id: "rja467ea",
    flightNumber: "RJA467",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Chengdu Tianfu",
    toCode: "ZUTF",
    region: "east-asia",
    duration: "5h 30m",
    frequency: "5x weekly",
    fromPrice: 43000,
    type: "passenger",
  },
  {
    id: "rja469",
    flightNumber: "RJA469",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Xi'an",
    toCode: "ZLXY",
    region: "east-asia",
    duration: "4h 45m",
    frequency: "4x weekly",
    fromPrice: 39000,
    type: "passenger",
  },
  {
    id: "rja471ea",
    flightNumber: "RJA471",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Wuhan",
    toCode: "ZHHH",
    region: "east-asia",
    duration: "4h 20m",
    frequency: "4x weekly",
    fromPrice: 37000,
    type: "passenger",
  },
  {
    id: "rja473ea",
    flightNumber: "RJA473",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Harbin",
    toCode: "ZYHB",
    region: "east-asia",
    duration: "3h 30m",
    frequency: "3x weekly",
    fromPrice: 34000,
    type: "passenger",
  },
  {
    id: "rja475",
    flightNumber: "RJA475",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Changsha",
    toCode: "ZGHA",
    region: "east-asia",
    duration: "4h 50m",
    frequency: "3x weekly",
    fromPrice: 40000,
    type: "passenger",
  },
  {
    id: "rja477",
    flightNumber: "RJA477",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Nanjing",
    toCode: "ZSNJ",
    region: "east-asia",
    duration: "3h 40m",
    frequency: "4x weekly",
    fromPrice: 35000,
    type: "passenger",
  },
  {
    id: "rja479",
    flightNumber: "RJA479",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Fuzhou",
    toCode: "ZSFZ",
    region: "east-asia",
    duration: "3h 50m",
    frequency: "3x weekly",
    fromPrice: 36000,
    type: "passenger",
  },
  {
    id: "rja481",
    flightNumber: "RJA481",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Qingdao",
    toCode: "ZSQD",
    region: "east-asia",
    duration: "3h 20m",
    frequency: "4x weekly",
    fromPrice: 33000,
    type: "passenger",
  },
  {
    id: "rja483",
    flightNumber: "RJA483",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Dalian",
    toCode: "ZYTL",
    region: "east-asia",
    duration: "3h 0m",
    frequency: "3x weekly",
    fromPrice: 31000,
    type: "passenger",
  },

  // Domestic Japan - Haneda (RJA451-478)
  {
    id: "rja451",
    flightNumber: "RJA451",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Aomori",
    toCode: "RJSA",
    region: "domestic",
    duration: "1h 20m",
    frequency: "Daily",
    fromPrice: 13000,
    type: "passenger",
  },
  {
    id: "rja453",
    flightNumber: "RJA453",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Asahikawa",
    toCode: "RJEC",
    region: "domestic",
    duration: "1h 40m",
    frequency: "Daily",
    fromPrice: 15000,
    type: "passenger",
  },
  {
    id: "rja455",
    flightNumber: "RJA455",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Fukuoka",
    toCode: "RJFF",
    region: "domestic",
    duration: "2h 0m",
    frequency: "Multiple daily",
    fromPrice: 18000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja457",
    flightNumber: "RJA457",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Hakodate",
    toCode: "RJCH",
    region: "domestic",
    duration: "1h 20m",
    frequency: "Daily",
    fromPrice: 13000,
    type: "passenger",
  },
  {
    id: "rja459",
    flightNumber: "RJA459",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Oita",
    toCode: "RJFO",
    region: "domestic",
    duration: "1h 50m",
    frequency: "Daily",
    fromPrice: 16000,
    type: "passenger",
  },
  {
    id: "rja461d",
    flightNumber: "RJA461",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Naha, Okinawa",
    toCode: "ROAH",
    region: "domestic",
    duration: "2h 45m",
    frequency: "Multiple daily",
    fromPrice: 22000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja463d",
    flightNumber: "RJA463",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Saga",
    toCode: "RJFS",
    region: "domestic",
    duration: "2h 5m",
    frequency: "Daily",
    fromPrice: 18500,
    type: "passenger",
  },
  {
    id: "rja465d",
    flightNumber: "RJA465",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Kochi",
    toCode: "RJOK",
    region: "domestic",
    duration: "1h 25m",
    frequency: "Daily",
    fromPrice: 14000,
    type: "passenger",
  },
  {
    id: "rja467",
    flightNumber: "RJA467",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Osaka Kansai",
    toCode: "RJBB",
    region: "domestic",
    duration: "1h 15m",
    frequency: "Multiple daily",
    fromPrice: 12000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja469d",
    flightNumber: "RJA469",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Miyazaki",
    toCode: "RJFM",
    region: "domestic",
    duration: "1h 55m",
    frequency: "Daily",
    fromPrice: 17000,
    type: "passenger",
  },
  {
    id: "rja471",
    flightNumber: "RJA471",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Osaka Itami",
    toCode: "RJOO",
    region: "domestic",
    duration: "1h 10m",
    frequency: "Multiple daily",
    fromPrice: 11500,
    type: "passenger",
  },
  {
    id: "rja473",
    flightNumber: "RJA473",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Hiroshima",
    toCode: "RJOA",
    region: "domestic",
    duration: "1h 30m",
    frequency: "Daily",
    fromPrice: 14000,
    type: "passenger",
  },
  {
    id: "rja475d",
    flightNumber: "RJA475",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Wakkanai",
    toCode: "RJCW",
    region: "domestic",
    duration: "2h 0m",
    frequency: "Daily",
    fromPrice: 18000,
    type: "passenger",
  },
  {
    id: "rja477",
    flightNumber: "RJA477",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Ishigaki",
    toCode: "ROIG",
    region: "domestic",
    duration: "3h 10m",
    frequency: "Daily",
    fromPrice: 25000,
    type: "passenger",
  },

  // Domestic Japan - Narita (RJA501-512)
  {
    id: "rja501",
    flightNumber: "RJA501",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "Shizuoka",
    toCode: "RJNS",
    region: "domestic",
    duration: "1h 0m",
    frequency: "Daily",
    fromPrice: 10000,
    type: "passenger",
  },
  {
    id: "rja503",
    flightNumber: "RJA503",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "Toyama",
    toCode: "RJNT",
    region: "domestic",
    duration: "1h 5m",
    frequency: "Daily",
    fromPrice: 10500,
    type: "passenger",
  },
  {
    id: "rja505",
    flightNumber: "RJA505",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "Akita",
    toCode: "RJSK",
    region: "domestic",
    duration: "1h 15m",
    frequency: "Daily",
    fromPrice: 12000,
    type: "passenger",
  },
  {
    id: "rja507",
    flightNumber: "RJA507",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "Hakodate",
    toCode: "RJCH",
    region: "domestic",
    duration: "1h 25m",
    frequency: "Daily",
    fromPrice: 13500,
    type: "passenger",
  },
  {
    id: "rja509",
    flightNumber: "RJA509",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "Matsuyama",
    toCode: "RJOM",
    region: "domestic",
    duration: "1h 30m",
    frequency: "Daily",
    fromPrice: 14000,
    type: "passenger",
  },
  {
    id: "rja511",
    flightNumber: "RJA511",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "Amami Ōshima",
    toCode: "RJKA",
    region: "domestic",
    duration: "2h 30m",
    frequency: "Daily",
    fromPrice: 20000,
    type: "passenger",
  },

  {
    id: "rja513",
    flightNumber: "RJA513",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Wakkanai",
    toCode: "RJCW",
    region: "domestic",
    duration: "50m",
    frequency: "Daily",
    fromPrice: 9500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja515",
    flightNumber: "RJA515",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Nakashibetsu",
    toCode: "RJCN",
    region: "domestic",
    duration: "45m",
    frequency: "Daily",
    fromPrice: 9000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja517",
    flightNumber: "RJA517",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Hakodate",
    toCode: "RJCH",
    region: "domestic",
    duration: "40m",
    frequency: "Daily",
    fromPrice: 8500,
    type: "passenger",
  },
  {
    id: "rja519",
    flightNumber: "RJA519",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Memanbetsu",
    toCode: "RJCM",
    region: "domestic",
    duration: "45m",
    frequency: "Daily",
    fromPrice: 9000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja521",
    flightNumber: "RJA521",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Kushiro",
    toCode: "RJCK",
    region: "domestic",
    duration: "45m",
    frequency: "Daily",
    fromPrice: 9000,
    type: "passenger",
  },
  {
    id: "rja523",
    flightNumber: "RJA523",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Obihiro",
    toCode: "RJCB",
    region: "domestic",
    duration: "40m",
    frequency: "Daily",
    fromPrice: 8500,
    type: "passenger",
  },
  {
    id: "rja525",
    flightNumber: "RJA525",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Okushiri",
    toCode: "RJCO",
    region: "domestic",
    duration: "50m",
    frequency: "3x weekly",
    fromPrice: 9500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja527",
    flightNumber: "RJA527",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Monbetsu",
    toCode: "RJEB",
    region: "domestic",
    duration: "55m",
    frequency: "Daily",
    fromPrice: 10000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja529",
    flightNumber: "RJA529",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Tokyo Haneda",
    toCode: "RJTT",
    region: "domestic",
    duration: "1h 35m",
    frequency: "Multiple daily",
    fromPrice: 15000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja531",
    flightNumber: "RJA531",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Tokyo Narita",
    toCode: "RJAA",
    region: "domestic",
    duration: "1h 40m",
    frequency: "Daily",
    fromPrice: 16000,
    type: "passenger",
  },
  {
    id: "rja533",
    flightNumber: "RJA533",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Osaka Kansai",
    toCode: "RJBB",
    region: "domestic",
    duration: "2h 0m",
    frequency: "Multiple daily",
    fromPrice: 18000,
    type: "passenger",
  },
  {
    id: "rja535",
    flightNumber: "RJA535",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Nagoya Chubu",
    toCode: "RJGG",
    region: "domestic",
    duration: "1h 50m",
    frequency: "Daily",
    fromPrice: 17000,
    type: "passenger",
  },
  {
    id: "rja537",
    flightNumber: "RJA537",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Rishiri",
    toCode: "RJER",
    region: "domestic",
    duration: "55m",
    frequency: "Daily",
    fromPrice: 10000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja539",
    flightNumber: "RJA539",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Osaka Itami",
    toCode: "RJOO",
    region: "domestic",
    duration: "2h 0m",
    frequency: "Daily",
    fromPrice: 18000,
    type: "passenger",
  },

  {
    id: "rja541",
    flightNumber: "RJA541",
    from: "Asahikawa",
    fromCode: "RJEC",
    to: "Tokyo Haneda",
    toCode: "RJTT",
    region: "domestic",
    duration: "1h 40m",
    frequency: "Daily",
    fromPrice: 15000,
    type: "passenger",
  },
  {
    id: "rja543",
    flightNumber: "RJA543",
    from: "Asahikawa",
    fromCode: "RJEC",
    to: "Tokyo Narita",
    toCode: "RJAA",
    region: "domestic",
    duration: "1h 45m",
    frequency: "Daily",
    fromPrice: 16000,
    type: "passenger",
  },
  {
    id: "rja545",
    flightNumber: "RJA545",
    from: "Asahikawa",
    fromCode: "RJEC",
    to: "New Chitose (Sapporo)",
    toCode: "RJCC",
    region: "domestic",
    duration: "35m",
    frequency: "Multiple daily",
    fromPrice: 7500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja547",
    flightNumber: "RJA547",
    from: "Asahikawa",
    fromCode: "RJEC",
    to: "Monbetsu",
    toCode: "RJEB",
    region: "domestic",
    duration: "30m",
    frequency: "Daily",
    fromPrice: 7000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja549",
    flightNumber: "RJA549",
    from: "Asahikawa",
    fromCode: "RJEC",
    to: "Misawa",
    toCode: "RJSM",
    region: "domestic",
    duration: "1h 10m",
    frequency: "Daily",
    fromPrice: 11000,
    type: "passenger",
  },
  {
    id: "rja551",
    flightNumber: "RJA551",
    from: "Asahikawa",
    fromCode: "RJEC",
    to: "Nagoya Chubu",
    toCode: "RJGG",
    region: "domestic",
    duration: "1h 55m",
    frequency: "Daily",
    fromPrice: 17000,
    type: "passenger",
  },
  {
    id: "rja553",
    flightNumber: "RJA553",
    from: "Asahikawa",
    fromCode: "RJEC",
    to: "Naha, Okinawa",
    toCode: "ROAH",
    region: "domestic",
    duration: "3h 30m",
    frequency: "3x weekly",
    fromPrice: 28000,
    type: "passenger",
  },

  {
    id: "rja555",
    flightNumber: "RJA555",
    from: "Osaka Kansai",
    fromCode: "RJBB",
    to: "Tokyo Narita",
    toCode: "RJAA",
    region: "domestic",
    duration: "1h 10m",
    frequency: "Multiple daily",
    fromPrice: 12000,
    type: "passenger",
  },
  {
    id: "rja557",
    flightNumber: "RJA557",
    from: "Osaka Kansai",
    fromCode: "RJBB",
    to: "Tokyo Haneda",
    toCode: "RJTT",
    region: "domestic",
    duration: "1h 5m",
    frequency: "Multiple daily",
    fromPrice: 11500,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja559",
    flightNumber: "RJA559",
    from: "Osaka Kansai",
    fromCode: "RJBB",
    to: "New Chitose (Sapporo)",
    toCode: "RJCC",
    region: "domestic",
    duration: "2h 0m",
    frequency: "Daily",
    fromPrice: 18000,
    type: "passenger",
  },
  {
    id: "rja561",
    flightNumber: "RJA561",
    from: "Osaka Kansai",
    fromCode: "RJBB",
    to: "Osaka Itami",
    toCode: "RJOO",
    region: "domestic",
    duration: "20m",
    frequency: "Multiple daily",
    fromPrice: 5000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja563",
    flightNumber: "RJA563",
    from: "Osaka Kansai",
    fromCode: "RJBB",
    to: "Hiroshima",
    toCode: "RJOA",
    region: "domestic",
    duration: "50m",
    frequency: "Daily",
    fromPrice: 9500,
    type: "passenger",
  },
  {
    id: "rja565",
    flightNumber: "RJA565",
    from: "Osaka Kansai",
    fromCode: "RJBB",
    to: "Kagoshima",
    toCode: "RJFK",
    region: "domestic",
    duration: "1h 20m",
    frequency: "Daily",
    fromPrice: 13000,
    type: "passenger",
  },
  {
    id: "rja567",
    flightNumber: "RJA567",
    from: "Osaka Kansai",
    fromCode: "RJBB",
    to: "Niigata",
    toCode: "RJSN",
    region: "domestic",
    duration: "1h 0m",
    frequency: "Daily",
    fromPrice: 10500,
    type: "passenger",
  },

  {
    id: "rja569",
    flightNumber: "RJA569",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "Tokyo Haneda",
    toCode: "RJTT",
    region: "domestic",
    duration: "25m",
    frequency: "Multiple daily",
    fromPrice: 6000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja571",
    flightNumber: "RJA571",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "New Chitose (Sapporo)",
    toCode: "RJCC",
    region: "domestic",
    duration: "1h 40m",
    frequency: "Daily",
    fromPrice: 16000,
    type: "passenger",
  },
  {
    id: "rja573",
    flightNumber: "RJA573",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "Asahikawa",
    toCode: "RJEC",
    region: "domestic",
    duration: "1h 45m",
    frequency: "Daily",
    fromPrice: 16500,
    type: "passenger",
  },
  {
    id: "rja575",
    flightNumber: "RJA575",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "Niigata",
    toCode: "RJSN",
    region: "domestic",
    duration: "1h 0m",
    frequency: "Daily",
    fromPrice: 10000,
    type: "passenger",
  },
  {
    id: "rja577",
    flightNumber: "RJA577",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "Hiroshima",
    toCode: "RJOA",
    region: "domestic",
    duration: "1h 30m",
    frequency: "Daily",
    fromPrice: 14000,
    type: "passenger",
  },
  {
    id: "rja579",
    flightNumber: "RJA579",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "Hachijojima",
    toCode: "RJTH",
    region: "domestic",
    duration: "55m",
    frequency: "Daily",
    fromPrice: 10000,
    type: "passenger",
    aircraft: "ATR-72",
  },

  {
    id: "rja581",
    flightNumber: "RJA581",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Hachijojima",
    toCode: "RJTH",
    region: "domestic",
    duration: "50m",
    frequency: "Daily",
    fromPrice: 9500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja583",
    flightNumber: "RJA583",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Kochi",
    toCode: "RJOK",
    region: "domestic",
    duration: "1h 25m",
    frequency: "Daily",
    fromPrice: 13500,
    type: "passenger",
  },
  {
    id: "rja585",
    flightNumber: "RJA585",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Nagasaki",
    toCode: "RJFU",
    region: "domestic",
    duration: "2h 5m",
    frequency: "Daily",
    fromPrice: 18500,
    type: "passenger",
  },
  {
    id: "rja587",
    flightNumber: "RJA587",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Rishiri",
    toCode: "RJER",
    region: "domestic",
    duration: "2h 10m",
    frequency: "Daily",
    fromPrice: 19000,
    type: "passenger",
  },
  {
    id: "rja589",
    flightNumber: "RJA589",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Monbetsu",
    toCode: "RJEB",
    region: "domestic",
    duration: "1h 50m",
    frequency: "Daily",
    fromPrice: 16500,
    type: "passenger",
  },
  {
    id: "rja591",
    flightNumber: "RJA591",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Niigata",
    toCode: "RJSN",
    region: "domestic",
    duration: "1h 5m",
    frequency: "Daily",
    fromPrice: 11000,
    type: "passenger",
  },
  {
    id: "rja593",
    flightNumber: "RJA593",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Obihiro",
    toCode: "RJCB",
    region: "domestic",
    duration: "1h 30m",
    frequency: "Daily",
    fromPrice: 14000,
    type: "passenger",
  },
  {
    id: "rja595",
    flightNumber: "RJA595",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Okinoerabu",
    toCode: "RJKB",
    region: "domestic",
    duration: "2h 40m",
    frequency: "3x weekly",
    fromPrice: 21000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja597",
    flightNumber: "RJA597",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Shonai",
    toCode: "RJSY",
    region: "domestic",
    duration: "1h 10m",
    frequency: "Daily",
    fromPrice: 11500,
    type: "passenger",
  },
  {
    id: "rja599",
    flightNumber: "RJA599",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Miyazaki",
    toCode: "RJFM",
    region: "domestic",
    duration: "1h 55m",
    frequency: "Daily",
    fromPrice: 17000,
    type: "passenger",
  },
  {
    id: "rja601",
    flightNumber: "RJA601",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Komatsu",
    toCode: "RJNK",
    region: "domestic",
    duration: "1h 5m",
    frequency: "Daily",
    fromPrice: 11000,
    type: "passenger",
  },
  {
    id: "rja603",
    flightNumber: "RJA603",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Yamagata",
    toCode: "RJSC",
    region: "domestic",
    duration: "1h 0m",
    frequency: "Daily",
    fromPrice: 10500,
    type: "passenger",
  },
  {
    id: "rja605",
    flightNumber: "RJA605",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Naha, Okinawa",
    toCode: "ROAH",
    region: "domestic",
    duration: "2h 45m",
    frequency: "Multiple daily",
    fromPrice: 22000,
    popular: true,
    type: "passenger",
  },

  {
    id: "rja607",
    flightNumber: "RJA607",
    from: "Hachijojima",
    fromCode: "RJTH",
    to: "Tokyo Haneda",
    toCode: "RJTT",
    region: "domestic",
    duration: "50m",
    frequency: "Daily",
    fromPrice: 9500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja609",
    flightNumber: "RJA609",
    from: "Hachijojima",
    fromCode: "RJTH",
    to: "Tokyo Narita",
    toCode: "RJAA",
    region: "domestic",
    duration: "55m",
    frequency: "Daily",
    fromPrice: 10000,
    type: "passenger",
    aircraft: "ATR-72",
  },

  {
    id: "rja611",
    flightNumber: "RJA611",
    from: "Naha, Okinawa",
    fromCode: "ROAH",
    to: "Miyako",
    toCode: "ROMY",
    region: "domestic",
    duration: "45m",
    frequency: "Multiple daily",
    fromPrice: 9000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja613",
    flightNumber: "RJA613",
    from: "Naha, Okinawa",
    fromCode: "ROAH",
    to: "Ishigaki",
    toCode: "ROIG",
    region: "domestic",
    duration: "1h 0m",
    frequency: "Multiple daily",
    fromPrice: 10500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja615",
    flightNumber: "RJA615",
    from: "Naha, Okinawa",
    fromCode: "ROAH",
    to: "Kumejima",
    toCode: "ROKJ",
    region: "domestic",
    duration: "35m",
    frequency: "Daily",
    fromPrice: 8000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja617",
    flightNumber: "RJA617",
    from: "Naha, Okinawa",
    fromCode: "ROAH",
    to: "Yonaguni",
    toCode: "ROYN",
    region: "domestic",
    duration: "1h 20m",
    frequency: "Daily",
    fromPrice: 13000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja619",
    flightNumber: "RJA619",
    from: "Naha, Okinawa",
    fromCode: "ROAH",
    to: "Tokyo Haneda",
    toCode: "RJTT",
    region: "domestic",
    duration: "2h 45m",
    frequency: "Multiple daily",
    fromPrice: 22000,
    popular: true,
    type: "passenger",
  },
  {
    id: "rja621",
    flightNumber: "RJA621",
    from: "Naha, Okinawa",
    fromCode: "ROAH",
    to: "Asahikawa",
    toCode: "RJEC",
    region: "domestic",
    duration: "3h 30m",
    frequency: "3x weekly",
    fromPrice: 28000,
    type: "passenger",
  },
  {
    id: "rja623",
    flightNumber: "RJA623",
    from: "Naha, Okinawa",
    fromCode: "ROAH",
    to: "Osaka Kansai",
    toCode: "RJBB",
    region: "domestic",
    duration: "2h 15m",
    frequency: "Daily",
    fromPrice: 19000,
    type: "passenger",
  },
  {
    id: "rja625",
    flightNumber: "RJA625",
    from: "Naha, Okinawa",
    fromCode: "ROAH",
    to: "Kikai",
    toCode: "RJKI",
    region: "domestic",
    duration: "1h 10m",
    frequency: "Daily",
    fromPrice: 11500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja627",
    flightNumber: "RJA627",
    from: "Naha, Okinawa",
    fromCode: "ROAH",
    to: "Amami Ōshima",
    toCode: "RJKA",
    region: "domestic",
    duration: "1h 5m",
    frequency: "Daily",
    fromPrice: 11000,
    type: "passenger",
    aircraft: "ATR-72",
  },

  {
    id: "rja629",
    flightNumber: "RJA629",
    from: "Miyako",
    fromCode: "ROMY",
    to: "Ishigaki",
    toCode: "ROIG",
    region: "domestic",
    duration: "30m",
    frequency: "Daily",
    fromPrice: 7500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja631",
    flightNumber: "RJA631",
    from: "Ishigaki",
    fromCode: "ROIG",
    to: "Kumejima",
    toCode: "ROKJ",
    region: "domestic",
    duration: "55m",
    frequency: "Daily",
    fromPrice: 10000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja633",
    flightNumber: "RJA633",
    from: "Kumejima",
    fromCode: "ROKJ",
    to: "Yonaguni",
    toCode: "ROYN",
    region: "domestic",
    duration: "1h 15m",
    frequency: "Daily",
    fromPrice: 12500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja635",
    flightNumber: "RJA635",
    from: "Yonaguni",
    fromCode: "ROYN",
    to: "Naha, Okinawa",
    toCode: "ROAH",
    region: "domestic",
    duration: "1h 20m",
    frequency: "Daily",
    fromPrice: 13000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja637",
    flightNumber: "RJA637",
    from: "Naha, Okinawa",
    fromCode: "ROAH",
    to: "Amami Ōshima",
    toCode: "RJKA",
    region: "domestic",
    duration: "1h 5m",
    frequency: "Daily",
    fromPrice: 11000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja639",
    flightNumber: "RJA639",
    from: "Amami Ōshima",
    fromCode: "RJKA",
    to: "Kikai",
    toCode: "RJKI",
    region: "domestic",
    duration: "25m",
    frequency: "Daily",
    fromPrice: 6500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja641",
    flightNumber: "RJA641",
    from: "Naha, Okinawa",
    fromCode: "ROAH",
    to: "Yoron",
    toCode: "RORY",
    region: "domestic",
    duration: "40m",
    frequency: "Daily",
    fromPrice: 8500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja643",
    flightNumber: "RJA643",
    from: "Miyako",
    fromCode: "ROMY",
    to: "Yoron",
    toCode: "RORY",
    region: "domestic",
    duration: "1h 10m",
    frequency: "3x weekly",
    fromPrice: 11500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja645",
    flightNumber: "RJA645",
    from: "Ishigaki",
    fromCode: "ROIG",
    to: "Tarama",
    toCode: "RORT",
    region: "domestic",
    duration: "35m",
    frequency: "3x weekly",
    fromPrice: 8000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja647",
    flightNumber: "RJA647",
    from: "Yonaguni",
    fromCode: "ROYN",
    to: "Tarama",
    toCode: "RORT",
    region: "domestic",
    duration: "1h 5m",
    frequency: "3x weekly",
    fromPrice: 11000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja649",
    flightNumber: "RJA649",
    from: "Naha, Okinawa",
    fromCode: "ROAH",
    to: "Miyako",
    toCode: "ROMY",
    region: "domestic",
    duration: "45m",
    frequency: "Multiple daily",
    fromPrice: 9000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja651",
    flightNumber: "RJA651",
    from: "Miyako",
    fromCode: "ROMY",
    to: "Ishigaki",
    toCode: "ROIG",
    region: "domestic",
    duration: "30m",
    frequency: "Daily",
    fromPrice: 7500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja653",
    flightNumber: "RJA653",
    from: "Ishigaki",
    fromCode: "ROIG",
    to: "Kumejima",
    toCode: "ROKJ",
    region: "domestic",
    duration: "55m",
    frequency: "Daily",
    fromPrice: 10000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja655",
    flightNumber: "RJA655",
    from: "Kumejima",
    fromCode: "ROKJ",
    to: "Yonaguni",
    toCode: "ROYN",
    region: "domestic",
    duration: "1h 15m",
    frequency: "Daily",
    fromPrice: 12500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja657",
    flightNumber: "RJA657",
    from: "Yonaguni",
    fromCode: "ROYN",
    to: "Naha, Okinawa",
    toCode: "ROAH",
    region: "domestic",
    duration: "1h 20m",
    frequency: "Daily",
    fromPrice: 13000,
    type: "passenger",
    aircraft: "ATR-72",
  },

  {
    id: "rja659",
    flightNumber: "RJA659",
    from: "Okinoerabu",
    fromCode: "RJKB",
    to: "Oki",
    toCode: "RJNO",
    region: "domestic",
    duration: "2h 15m",
    frequency: "3x weekly",
    fromPrice: 19000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja661",
    flightNumber: "RJA661",
    from: "Obihiro",
    fromCode: "RJCB",
    to: "Oki",
    toCode: "RJNO",
    region: "domestic",
    duration: "2h 30m",
    frequency: "3x weekly",
    fromPrice: 20000,
    type: "passenger",
  },
  {
    id: "rja663",
    flightNumber: "RJA663",
    from: "Tokushima",
    fromCode: "RJOS",
    to: "Oki",
    toCode: "RJNO",
    region: "domestic",
    duration: "1h 15m",
    frequency: "Daily",
    fromPrice: 12500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja665",
    flightNumber: "RJA665",
    from: "Okinoerabu",
    fromCode: "RJKB",
    to: "Tokushima",
    toCode: "RJOS",
    region: "domestic",
    duration: "1h 50m",
    frequency: "3x weekly",
    fromPrice: 16500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja667",
    flightNumber: "RJA667",
    from: "Tokushima",
    fromCode: "RJOS",
    to: "Obihiro",
    toCode: "RJCB",
    region: "domestic",
    duration: "2h 10m",
    frequency: "Daily",
    fromPrice: 18500,
    type: "passenger",
  },

  {
    id: "rja669",
    flightNumber: "RJA669",
    from: "Wakkanai",
    fromCode: "RJCW",
    to: "Nakashibetsu",
    toCode: "RJCN",
    region: "domestic",
    duration: "1h 10m",
    frequency: "Daily",
    fromPrice: 11500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja671",
    flightNumber: "RJA671",
    from: "Wakkanai",
    fromCode: "RJCW",
    to: "Rebun",
    toCode: "RJCR",
    region: "domestic",
    duration: "25m",
    frequency: "Daily",
    fromPrice: 6500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja673",
    flightNumber: "RJA673",
    from: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    to: "Nakashibetsu",
    toCode: "RJCN",
    region: "domestic",
    duration: "45m",
    frequency: "Daily",
    fromPrice: 9000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja675",
    flightNumber: "RJA675",
    from: "Wakkanai",
    fromCode: "RJCW",
    to: "New Chitose (Sapporo)",
    fromCode: "RJCC",
    region: "domestic",
    duration: "50m",
    frequency: "Daily",
    fromPrice: 9500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja677",
    flightNumber: "RJA677",
    from: "Rebun",
    fromCode: "RJCR",
    to: "New Chitose (Sapporo)",
    toCode: "RJCC",
    region: "domestic",
    duration: "1h 10m",
    frequency: "Daily",
    fromPrice: 11500,
    type: "passenger",
    aircraft: "ATR-72",
  },

  {
    id: "rja679",
    flightNumber: "RJA679",
    from: "Kagoshima",
    fromCode: "RJFK",
    to: "Okinoerabu",
    toCode: "RJKB",
    region: "domestic",
    duration: "1h 10m",
    frequency: "Daily",
    fromPrice: 11500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja681",
    flightNumber: "RJA681",
    from: "Okinoerabu",
    fromCode: "RJKB",
    to: "Amami Ōshima",
    toCode: "RJKA",
    region: "domestic",
    duration: "35m",
    frequency: "Daily",
    fromPrice: 8000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja683",
    flightNumber: "RJA683",
    from: "Kagoshima",
    fromCode: "RJFK",
    to: "Amami Ōshima",
    toCode: "RJKA",
    region: "domestic",
    duration: "1h 5m",
    frequency: "Daily",
    fromPrice: 11000,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja685",
    flightNumber: "RJA685",
    from: "Miyazaki",
    fromCode: "RJFM",
    to: "Amami Ōshima",
    toCode: "RJKA",
    region: "domestic",
    duration: "1h 15m",
    frequency: "Daily",
    fromPrice: 12500,
    type: "passenger",
    aircraft: "ATR-72",
  },

  {
    id: "rja687",
    flightNumber: "RJA687",
    from: "Niigata",
    fromCode: "RJSN",
    to: "Monbetsu",
    toCode: "RJEB",
    region: "domestic",
    duration: "1h 25m",
    frequency: "Daily",
    fromPrice: 13500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja689",
    flightNumber: "RJA689",
    from: "Rishiri",
    fromCode: "RJER",
    to: "Nakashibetsu",
    toCode: "RJCN",
    region: "domestic",
    duration: "1h 15m",
    frequency: "Daily",
    fromPrice: 12500,
    type: "passenger",
    aircraft: "ATR-72",
  },
  {
    id: "rja691",
    flightNumber: "RJA691",
    from: "Aomori",
    fromCode: "RJSA",
    to: "Shonai",
    toCode: "RJSY",
    region: "domestic",
    duration: "45m",
    frequency: "Daily",
    fromPrice: 9000,
    type: "passenger",
    aircraft: "ATR-72",
  },

  // Codeshare Routes - Pacific Airlines
  {
    id: "rja201cs",
    flightNumber: "RJA201",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Montreal",
    toCode: "CYUL",
    region: "north-america",
    duration: "13h 0m",
    frequency: "5x weekly",
    fromPrice: 92000,
    type: "passenger",
    codeshare: "Pacific Airlines",
  },
  {
    id: "rja202",
    flightNumber: "RJA202",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Toronto",
    toCode: "CYYZ",
    region: "north-america",
    duration: "12h 30m",
    frequency: "Daily",
    fromPrice: 91000,
    type: "passenger",
    codeshare: "Pacific Airlines",
  },
  {
    id: "rja203",
    flightNumber: "RJA203",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Vancouver",
    toCode: "CYVR",
    region: "north-america",
    duration: "9h 30m",
    frequency: "Daily",
    fromPrice: 85000,
    type: "passenger",
    codeshare: "Pacific Airlines",
  },
  {
    id: "rja204",
    flightNumber: "RJA204",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Ottawa",
    toCode: "CYOW",
    region: "north-america",
    duration: "13h 15m",
    frequency: "3x weekly",
    fromPrice: 93000,
    type: "passenger",
    codeshare: "Pacific Airlines",
  },
  {
    id: "rja205",
    flightNumber: "RJA205",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Panama City",
    toCode: "MPTO",
    region: "south-america",
    duration: "16h 30m",
    frequency: "2x weekly",
    fromPrice: 125000,
    type: "passenger",
    codeshare: "Pacific Airlines",
  },
  {
    id: "rja206",
    flightNumber: "RJA206",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Portland",
    toCode: "KPDX",
    region: "north-america",
    duration: "10h 0m",
    frequency: "4x weekly",
    fromPrice: 87000,
    type: "passenger",
    codeshare: "Pacific Airlines",
  },
  {
    id: "rja207",
    flightNumber: "RJA207",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Seattle",
    toCode: "KSEA",
    region: "north-america",
    duration: "9h 45m",
    frequency: "Daily",
    fromPrice: 86000,
    type: "passenger",
    codeshare: "Pacific Airlines",
  },
  {
    id: "rja208",
    flightNumber: "RJA208",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Philadelphia",
    toCode: "KPHL",
    region: "north-america",
    duration: "13h 40m",
    frequency: "4x weekly",
    fromPrice: 95000,
    type: "passenger",
    codeshare: "Pacific Airlines",
  },
  {
    id: "rja209cs",
    flightNumber: "RJA209",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "London Gatwick",
    toCode: "EGKK",
    region: "europe",
    duration: "12h 45m",
    frequency: "5x weekly",
    fromPrice: 86000,
    type: "passenger",
    codeshare: "Pacific Airlines",
  },

  // Codeshare Routes - Air Canada
  {
    id: "rja401cs",
    flightNumber: "RJA401",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Montreal",
    toCode: "CYUL",
    region: "north-america",
    duration: "13h 0m",
    frequency: "5x weekly",
    fromPrice: 92000,
    type: "passenger",
    codeshare: "Air Canada",
  },
  {
    id: "rja402",
    flightNumber: "RJA402",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Toronto",
    toCode: "CYYZ",
    region: "north-america",
    duration: "12h 30m",
    frequency: "Daily",
    fromPrice: 91000,
    type: "passenger",
    codeshare: "Air Canada",
  },
  {
    id: "rja403cs",
    flightNumber: "RJA403",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Vancouver",
    toCode: "CYVR",
    region: "north-america",
    duration: "9h 30m",
    frequency: "Daily",
    fromPrice: 85000,
    type: "passenger",
    codeshare: "Air Canada",
  },

  // Codeshare Routes - Turkish Airlines
  {
    id: "rja501cs",
    flightNumber: "RJA501",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Istanbul",
    toCode: "LTFM",
    region: "middle-east",
    duration: "12h 15m",
    frequency: "Daily",
    fromPrice: 79000,
    type: "passenger",
    codeshare: "Turkish Airlines",
  },
  {
    id: "rja502",
    flightNumber: "RJA502",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Ankara",
    toCode: "LTAC",
    region: "middle-east",
    duration: "12h 30m",
    frequency: "4x weekly",
    fromPrice: 80000,
    type: "passenger",
    codeshare: "Turkish Airlines",
  },
  {
    id: "rja503cs",
    flightNumber: "RJA503",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Izmir",
    toCode: "LTBJ",
    region: "middle-east",
    duration: "12h 45m",
    frequency: "3x weekly",
    fromPrice: 81000,
    type: "passenger",
    codeshare: "Turkish Airlines",
  },
  {
    id: "rja504",
    flightNumber: "RJA504",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Antalya",
    toCode: "LTAI",
    region: "middle-east",
    duration: "13h 0m",
    frequency: "3x weekly",
    fromPrice: 82000,
    type: "passenger",
    codeshare: "Turkish Airlines",
  },
  {
    id: "rja505",
    flightNumber: "RJA505",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Trabzon",
    toCode: "LTCG",
    region: "middle-east",
    duration: "13h 15m",
    frequency: "2x weekly",
    fromPrice: 83000,
    type: "passenger",
    codeshare: "Turkish Airlines",
  },

  // Codeshare Routes - Kittyo Airways
  {
    id: "rja601",
    flightNumber: "RJA601",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Sydney",
    toCode: "YSSY",
    region: "oceania",
    duration: "9h 45m",
    frequency: "Daily",
    fromPrice: 68000,
    type: "passenger",
    codeshare: "Kittyo Airways",
  },
  {
    id: "rja602",
    flightNumber: "RJA602",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Melbourne",
    toCode: "YMML",
    region: "oceania",
    duration: "10h 15m",
    frequency: "Daily",
    fromPrice: 69000,
    type: "passenger",
    codeshare: "Kittyo Airways",
  },
  {
    id: "rja603",
    flightNumber: "RJA603",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Perth",
    toCode: "YPPH",
    region: "oceania",
    duration: "10h 30m",
    frequency: "5x weekly",
    fromPrice: 70000,
    type: "passenger",
    codeshare: "Kittyo Airways",
  },
  {
    id: "rja604",
    flightNumber: "RJA604",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Brisbane",
    toCode: "YBBN",
    region: "oceania",
    duration: "9h 20m",
    frequency: "5x weekly",
    fromPrice: 67000,
    type: "passenger",
    codeshare: "Kittyo Airways",
  },
  {
    id: "rja605",
    flightNumber: "RJA605",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Auckland",
    toCode: "NZAA",
    region: "oceania",
    duration: "11h 0m",
    frequency: "5x weekly",
    fromPrice: 72000,
    type: "passenger",
    codeshare: "Kittyo Airways",
  },

  // Cargo Routes (RJC100-399)
  {
    id: "rjc101",
    flightNumber: "RJC101",
    from: "London Heathrow",
    fromCode: "EGLL",
    to: "Atlanta",
    toCode: "KATL",
    region: "cargo",
    duration: "9h 0m",
    frequency: "3x weekly",
    fromPrice: 0,
    type: "cargo",
    aircraft: "Boeing 747",
  },
  {
    id: "rjc103",
    flightNumber: "RJC103",
    from: "Toronto",
    fromCode: "CYYZ",
    to: "San Francisco",
    toCode: "KSFO",
    region: "cargo",
    duration: "5h 30m",
    frequency: "4x weekly",
    fromPrice: 0,
    type: "cargo",
    aircraft: "Boeing 747-8F",
  },
  {
    id: "rjc105",
    flightNumber: "RJC105",
    from: "Montreal",
    fromCode: "CYUL",
    to: "Frankfurt",
    toCode: "EDDF",
    region: "cargo",
    duration: "7h 30m",
    frequency: "3x weekly",
    fromPrice: 0,
    type: "cargo",
    aircraft: "Boeing 747F",
  },
  {
    id: "rjc107",
    flightNumber: "RJC107",
    from: "Dallas/Fort Worth",
    fromCode: "KDFW",
    to: "Paris CDG",
    toCode: "LFPG",
    region: "cargo",
    duration: "9h 30m",
    frequency: "3x weekly",
    fromPrice: 0,
    type: "cargo",
    aircraft: "Boeing 777F",
  },
  {
    id: "rjc109",
    flightNumber: "RJC109",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Chicago O'Hare",
    toCode: "KORD",
    region: "cargo",
    duration: "12h 0m",
    frequency: "Daily",
    fromPrice: 0,
    type: "cargo",
    aircraft: "Boeing 747-8F",
  },
  {
    id: "rjc201",
    flightNumber: "RJC201",
    from: "Amsterdam",
    fromCode: "EHAM",
    to: "Abu Dhabi",
    toCode: "OMAA",
    region: "cargo",
    duration: "6h 30m",
    frequency: "4x weekly",
    fromPrice: 0,
    type: "cargo",
    aircraft: "Boeing 747-8F",
  },
  {
    id: "rjc203",
    flightNumber: "RJC203",
    from: "Paris CDG",
    fromCode: "LFPG",
    to: "Doha",
    toCode: "OTHH",
    region: "cargo",
    duration: "6h 0m",
    frequency: "3x weekly",
    fromPrice: 0,
    type: "cargo",
    aircraft: "Boeing 777F",
  },
  {
    id: "rjc205",
    flightNumber: "RJC205",
    from: "Paris CDG",
    fromCode: "LFPG",
    to: "London Stansted",
    toCode: "EGSS",
    region: "cargo",
    duration: "1h 15m",
    frequency: "Daily",
    fromPrice: 0,
    type: "cargo",
    aircraft: "Boeing 777F",
  },
  {
    id: "rjc301",
    flightNumber: "RJC301",
    from: "Singapore",
    fromCode: "WSSS",
    to: "Hong Kong",
    toCode: "VHHH",
    region: "cargo",
    duration: "3h 45m",
    frequency: "Daily",
    fromPrice: 0,
    type: "cargo",
    aircraft: "Boeing 777F",
  },
  {
    id: "rjc303",
    flightNumber: "RJC303",
    from: "Mumbai",
    fromCode: "VABB",
    to: "London Heathrow",
    toCode: "EGLL",
    region: "cargo",
    duration: "9h 30m",
    frequency: "4x weekly",
    fromPrice: 0,
    type: "cargo",
    aircraft: "Boeing 777F",
  },
  {
    id: "rjc305",
    flightNumber: "RJC305",
    from: "Sydney",
    fromCode: "YSSY",
    to: "Auckland",
    toCode: "NZAA",
    region: "cargo",
    duration: "3h 15m",
    frequency: "5x weekly",
    fromPrice: 0,
    type: "cargo",
    aircraft: "Boeing 747",
  },

  // Supersonic Routes (RJA900-940)
  {
    id: "rja901",
    flightNumber: "RJA901",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Toronto",
    toCode: "CYYZ",
    region: "supersonic",
    duration: "6h 15m",
    frequency: "Daily",
    fromPrice: 250000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja903",
    flightNumber: "RJA903",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "New York JFK",
    toCode: "KJFK",
    region: "supersonic",
    duration: "6h 30m",
    frequency: "Daily",
    fromPrice: 260000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja905",
    flightNumber: "RJA905",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Montreal",
    toCode: "CYUL",
    region: "supersonic",
    duration: "6h 30m",
    frequency: "5x weekly",
    fromPrice: 255000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja907",
    flightNumber: "RJA907",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Anchorage",
    toCode: "PANC",
    region: "supersonic",
    duration: "4h 0m",
    frequency: "4x weekly",
    fromPrice: 180000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja909",
    flightNumber: "RJA909",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "San Francisco",
    toCode: "KSFO",
    region: "supersonic",
    duration: "5h 15m",
    frequency: "Daily",
    fromPrice: 220000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja911",
    flightNumber: "RJA911",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "London Heathrow",
    toCode: "EGLL",
    region: "supersonic",
    duration: "6h 15m",
    frequency: "Daily",
    fromPrice: 280000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja913",
    flightNumber: "RJA913",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Paris CDG",
    toCode: "LFPG",
    region: "supersonic",
    duration: "6h 30m",
    frequency: "Daily",
    fromPrice: 285000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja915",
    flightNumber: "RJA915",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Amsterdam",
    toCode: "EHAM",
    region: "supersonic",
    duration: "6h 20m",
    frequency: "5x weekly",
    fromPrice: 275000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja917",
    flightNumber: "RJA917",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Frankfurt",
    toCode: "EDDF",
    region: "supersonic",
    duration: "6h 25m",
    frequency: "5x weekly",
    fromPrice: 278000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja919",
    flightNumber: "RJA919",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Rome Fiumicino",
    toCode: "LIRF",
    region: "supersonic",
    duration: "7h 0m",
    frequency: "4x weekly",
    fromPrice: 290000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja921",
    flightNumber: "RJA921",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Zurich",
    toCode: "LSZH",
    region: "supersonic",
    duration: "6h 35m",
    frequency: "4x weekly",
    fromPrice: 282000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja923",
    flightNumber: "RJA923",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Reykjavik",
    toCode: "BIRK",
    region: "supersonic",
    duration: "7h 30m",
    frequency: "3x weekly",
    fromPrice: 295000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja931",
    flightNumber: "RJA931",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Sydney",
    toCode: "YSSY",
    region: "supersonic",
    duration: "4h 50m",
    frequency: "Daily",
    fromPrice: 200000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja933",
    flightNumber: "RJA933",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Hong Kong",
    toCode: "VHHH",
    region: "supersonic",
    duration: "2h 25m",
    frequency: "Daily",
    fromPrice: 150000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja935",
    flightNumber: "RJA935",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Kuala Lumpur",
    toCode: "WMKK",
    region: "supersonic",
    duration: "3h 45m",
    frequency: "5x weekly",
    fromPrice: 170000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja937",
    flightNumber: "RJA937",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Brisbane",
    toCode: "YBBN",
    region: "supersonic",
    duration: "4h 40m",
    frequency: "4x weekly",
    fromPrice: 195000,
    type: "supersonic",
    aircraft: "Concorde",
  },
  {
    id: "rja939",
    flightNumber: "RJA939",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Singapore",
    toCode: "WSSS",
    region: "supersonic",
    duration: "3h 40m",
    frequency: "Daily",
    fromPrice: 165000,
    type: "supersonic",
    aircraft: "Concorde",
  },

  // Seasonal Routes - Summer
  {
    id: "rja-summer-lisbon",
    flightNumber: "RJA117",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Lisbon",
    toCode: "LPPT",
    region: "europe",
    duration: "15h 10m",
    frequency: "3x weekly",
    fromPrice: 91000,
    type: "passenger",
    seasonal: "summer",
    aircraft: "A350-1000",
  },
  {
    id: "rja-summer-athens",
    flightNumber: "RJA-S01",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Athens",
    toCode: "LGAV",
    region: "europe",
    duration: "13h 30m",
    frequency: "3x weekly",
    fromPrice: 89000,
    type: "passenger",
    seasonal: "summer",
    aircraft: "B777-300ER",
  },
  {
    id: "rja-summer-vienna",
    flightNumber: "RJA-S02",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "Vienna",
    toCode: "LOWW",
    region: "europe",
    duration: "12h 40m",
    frequency: "3x weekly",
    fromPrice: 82000,
    type: "passenger",
    seasonal: "summer",
    aircraft: "A350-900",
  },
  {
    id: "rja-summer-vancouver",
    flightNumber: "RJA-S03",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Vancouver",
    toCode: "CYVR",
    region: "north-america",
    duration: "9h 30m",
    frequency: "Daily",
    fromPrice: 85000,
    type: "passenger",
    seasonal: "summer",
    aircraft: "B787-9",
  },
  {
    id: "rja-summer-boston",
    flightNumber: "RJA-S04",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Boston",
    toCode: "KBOS",
    region: "north-america",
    duration: "13h 30m",
    frequency: "Daily",
    fromPrice: 93000,
    type: "passenger",
    seasonal: "summer",
    aircraft: "B787-9",
  },
  {
    id: "rja-summer-barcelona",
    flightNumber: "RJA-S05",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Barcelona",
    toCode: "LEBL",
    region: "europe",
    duration: "14h 30m",
    frequency: "4x weekly",
    fromPrice: 89500,
    type: "passenger",
    seasonal: "summer",
    aircraft: "A350-1000",
  },

  // Seasonal Routes - Autumn
  {
    id: "rja-autumn-dubrovnik",
    flightNumber: "RJA-A01",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Dubrovnik",
    toCode: "LDDU",
    region: "europe",
    duration: "13h 45m",
    frequency: "2x weekly",
    fromPrice: 88000,
    type: "passenger",
    seasonal: "autumn",
    aircraft: "B787-9",
  },
  {
    id: "rja-autumn-istanbul",
    flightNumber: "RJA-A02",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Istanbul",
    toCode: "LTFM",
    region: "middle-east",
    duration: "12h 15m",
    frequency: "Daily",
    fromPrice: 79000,
    type: "passenger",
    seasonal: "autumn",
    aircraft: "A350-1000",
  },
  {
    id: "rja-autumn-santorini",
    flightNumber: "RJA-A03",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Santorini",
    toCode: "LGSR",
    region: "europe",
    duration: "14h 0m",
    frequency: "2x weekly",
    fromPrice: 92000,
    type: "passenger",
    seasonal: "autumn",
    aircraft: "B787-9",
  },
  {
    id: "rja-autumn-telaviv",
    flightNumber: "RJA-A04",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Tel Aviv",
    toCode: "LLBG",
    region: "middle-east",
    duration: "12h 45m",
    frequency: "3x weekly",
    fromPrice: 81000,
    type: "passenger",
    seasonal: "autumn",
    aircraft: "A350-1000",
  },
  {
    id: "rja-autumn-denver",
    flightNumber: "RJA-A05",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Denver",
    toCode: "KDEN",
    region: "north-america",
    duration: "11h 30m",
    frequency: "4x weekly",
    fromPrice: 90000,
    type: "passenger",
    seasonal: "autumn",
    aircraft: "B787-9",
  },
  {
    id: "rja-autumn-cairns",
    flightNumber: "RJA-A06",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Cairns",
    toCode: "YBCS",
    region: "oceania",
    duration: "8h 30m",
    frequency: "3x weekly",
    fromPrice: 64000,
    type: "passenger",
    seasonal: "autumn",
    aircraft: "B787-9",
  },

  {
    id: "rja471",
    flightNumber: "RJA471",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Osaka Itami",
    toCode: "RJOO",
    region: "domestic",
    duration: "1h 15m",
    frequency: "Daily",
    fromPrice: 12000,
    type: "passenger",
    codeshare: "Singapore Airlines",
  },
  {
    id: "rja472",
    flightNumber: "RJA472",
    from: "Osaka Itami",
    fromCode: "RJOO",
    to: "Tokyo Haneda",
    toCode: "RJTT",
    region: "domestic",
    duration: "1h 15m",
    frequency: "Daily",
    fromPrice: 12000,
    type: "passenger",
    codeshare: "Singapore Airlines",
  },
  {
    id: "rja411",
    flightNumber: "RJA411",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Taipei Songshan",
    toCode: "RCSS",
    region: "east-asia",
    duration: "3h 30m",
    frequency: "Daily",
    fromPrice: 28000,
    type: "passenger",
    codeshare: "Singapore Airlines",
  },
  {
    id: "rja412",
    flightNumber: "RJA412",
    from: "Taipei Songshan",
    fromCode: "RCSS",
    to: "Tokyo Haneda",
    toCode: "RJTT",
    region: "east-asia",
    duration: "3h 30m",
    frequency: "Daily",
    fromPrice: 28000,
    type: "passenger",
    codeshare: "Singapore Airlines",
  },
  {
    id: "rja463",
    flightNumber: "RJA463",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Shanghai Hongqiao",
    toCode: "ZSSS",
    region: "east-asia",
    duration: "3h 0m",
    frequency: "Daily",
    fromPrice: 32000,
    type: "passenger",
    codeshare: "Singapore Airlines",
  },
  {
    id: "rja464",
    flightNumber: "RJA464",
    from: "Shanghai Hongqiao",
    fromCode: "ZSSS",
    to: "Tokyo Haneda",
    toCode: "RJTT",
    region: "east-asia",
    duration: "3h 0m",
    frequency: "Daily",
    fromPrice: 32000,
    type: "passenger",
    codeshare: "Singapore Airlines",
  },
  // </CHANGE> Adding RJA codeshares on Singapore Airlines routes
  {
    id: "sia147",
    flightNumber: "SIA147",
    from: "Singapore Changi",
    fromCode: "WSSS",
    to: "Bandar Seri Begawan",
    toCode: "WBSB",
    region: "southeast-asia",
    duration: "2h 0m",
    frequency: "Daily",
    fromPrice: 18000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
  {
    id: "sia148",
    flightNumber: "SIA148",
    from: "Bandar Seri Begawan",
    fromCode: "WBSB",
    to: "Singapore Changi",
    toCode: "WSSS",
    region: "southeast-asia",
    duration: "2h 0m",
    frequency: "Daily",
    fromPrice: 18000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
  {
    id: "sia149",
    flightNumber: "SIA149",
    from: "Singapore Changi",
    fromCode: "WSSS",
    to: "Langkawi",
    toCode: "WMKL",
    region: "southeast-asia",
    duration: "1h 30m",
    frequency: "Daily",
    fromPrice: 15000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
  {
    id: "sia152",
    flightNumber: "SIA152",
    from: "Langkawi",
    fromCode: "WMKL",
    to: "Singapore Changi",
    toCode: "WSSS",
    region: "southeast-asia",
    duration: "1h 30m",
    frequency: "Daily",
    fromPrice: 15000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
  {
    id: "sia950",
    flightNumber: "SIA950",
    from: "Singapore Changi",
    fromCode: "WSSS",
    to: "Jakarta",
    toCode: "WIII",
    region: "southeast-asia",
    duration: "2h 0m",
    frequency: "Daily",
    fromPrice: 20000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
  {
    id: "sia968",
    flightNumber: "SIA968",
    from: "Jakarta",
    fromCode: "WIII",
    to: "Singapore Changi",
    toCode: "WSSS",
    region: "southeast-asia",
    duration: "2h 0m",
    frequency: "Daily",
    fromPrice: 20000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
  {
    id: "sia634",
    flightNumber: "SIA634",
    from: "Singapore Changi",
    fromCode: "WSSS",
    to: "Tokyo Haneda",
    toCode: "RJTT",
    region: "east-asia",
    duration: "6h 45m",
    frequency: "Daily",
    fromPrice: 45000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
  {
    id: "sia635",
    flightNumber: "SIA635",
    from: "Tokyo Haneda",
    fromCode: "RJTT",
    to: "Singapore Changi",
    toCode: "WSSS",
    region: "east-asia",
    duration: "6h 45m",
    frequency: "Daily",
    fromPrice: 45000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
  {
    id: "sia637",
    flightNumber: "SIA637",
    from: "Singapore Changi",
    fromCode: "WSSS",
    to: "Tokyo Narita",
    toCode: "RJAA",
    region: "east-asia",
    duration: "7h 0m",
    frequency: "Daily",
    fromPrice: 46000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
  {
    id: "sia638",
    flightNumber: "SIA638",
    from: "Tokyo Narita",
    fromCode: "RJAA",
    to: "Singapore Changi",
    toCode: "WSSS",
    region: "east-asia",
    duration: "7h 0m",
    frequency: "Daily",
    fromPrice: 46000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
  {
    id: "sia103",
    flightNumber: "SIA103",
    from: "Singapore Changi",
    fromCode: "WSSS",
    to: "Kuala Lumpur",
    toCode: "WMKK",
    region: "southeast-asia",
    duration: "1h 0m",
    frequency: "Daily",
    fromPrice: 12000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
  {
    id: "sia128",
    flightNumber: "SIA128",
    from: "Kuala Lumpur",
    fromCode: "WMKK",
    to: "Singapore Changi",
    toCode: "WSSS",
    region: "southeast-asia",
    duration: "1h 0m",
    frequency: "Daily",
    fromPrice: 12000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
  {
    id: "sia726",
    flightNumber: "SIA726",
    from: "Singapore Changi",
    fromCode: "WSSS",
    to: "Phuket",
    toCode: "VTSP",
    region: "southeast-asia",
    duration: "2h 15m",
    frequency: "Daily",
    fromPrice: 22000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
  {
    id: "sia740",
    flightNumber: "SIA740",
    from: "Phuket",
    fromCode: "VTSP",
    to: "Singapore Changi",
    toCode: "WSSS",
    region: "southeast-asia",
    duration: "2h 15m",
    frequency: "Daily",
    fromPrice: 22000,
    type: "passenger",
    codeshare: "Royal Japan Airlines",
  },
]

export const regions = [
  { value: "all", label: "All Routes" },
  { value: "europe", label: "Europe" },
  { value: "north-america", label: "North America" },
  { value: "south-america", label: "South America" },
  { value: "middle-east", label: "Middle East" },
  { value: "southeast-asia", label: "Southeast Asia" },
  { value: "south-asia", label: "South Asia" },
  { value: "east-asia", label: "East Asia" },
  { value: "central-asia", label: "Central Asia" },
  { value: "oceania", label: "Oceania" },
  { value: "russia", label: "Russia" },
  { value: "domestic", label: "Domestic Japan" },
  { value: "cargo", label: "Cargo Routes" },
  { value: "supersonic", label: "Supersonic Routes" },
]
